### ISSUE TITLE
share QR code -> bad quality

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#87] opened 2016-01-23 11:07 UTC
0.1.30.b2149

Since this release the shared QR code is too small (not enough pixel, quality very bad)

strange: when i edit name for my info and THEN share QR, quality is good as before.

**Comment by am4n0w4r** [comment] 2016-01-26 10:40
Couldn't reproduce this on any device, code is small for a moment right at startup but then gets resized to normal size. Please test in 0.1.31, tuned displaying mechanism a little, should work fine;

**Comment by SpiderBTT** [comment] 2016-01-26 11:41
I confirm, 100x100 pixels is too small.

**Comment by fyahfox** [comment] 2016-01-26 22:56
not fixed in 0.1.31

**Comment by am4n0w4r** [comment] 2016-01-28 16:20
Resolved in 0.1.32;

**Closed** 2016-01-31 17:20 UTC
Labels: bug, mustfix, resolved
