### ISSUE TITLE
Adding account via QR -> Camera picture sometimes does not focus

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#45] opened 2015-12-12 12:08 UTC
v0.1.24.b1495

Sometimes the camera picture does not focus. At least this happens for "Add new acount -> QR". I didn't check it for other QR scan places yet.

If this happens, then it doesn't scan successfully. Going back, and reopen the scan view sometimes helps, sometimes not. So I have to repeat going back and open scan view until it focuses.

**Comment by am4n0w4r** [comment] 2016-01-06 11:07
I commented this in #27 , guess this two can be merged as they related to the same scanner initialization issue.

**Comment by fyahfox** [comment] 2016-01-07 11:32
hm not sure. since 0.1.26 the QRs which are focused correctly are not recognized...

**Comment by am4n0w4r** [comment] 2016-01-18 11:22
Are there still issues with camera focusing in 0.1.28?

**Comment by fyahfox** [comment] 2016-01-18 12:55
yes, i sent a camera pic report (clicked in the pic) just a few seconds ago

**Comment by am4n0w4r** [comment] 2016-01-22 16:19
Please test this in 0.1.30, fixed weird bug in QR scanner that was due to inconsistent and undocumented Android realizations.

**Comment by fyahfox** [comment] 2016-01-24 13:51
Scanning works again, but only if focus issue doesnt happen.
I still experience focus problems (focus is fixed, doesnt refocus if I go closer to the QR) and then the scanning doesnt work.

**Comment by am4n0w4r** [comment] 2016-01-25 13:02
Is this reproducible on some particular device, or on different devices? Please send report by clicking on scanner preview as soon as possible when this issue arises. Also try to shake the device a little, or change it's position -  some phones try to refocus only if they think they are moved, not continuously.

**Comment by fyahfox** [comment] 2016-01-31 15:14
I still experience the focus problem in 0.1.32

report sent 10 seconds ago

**Comment by am4n0w4r** [comment] 2016-02-01 10:35
Thanks, I see the report but it is flooded with scanning messages. Can you please send report right after preview is shown? And one more question - does the problem happen always or sometimes?

**Comment by fyahfox** [comment] 2016-02-01 11:06
It happens sometimes, not always. Sometimes like 3 times in a row, so it is pretty annoying.

I can't send the report faster. I have to activate scan mode, check if it is focusing or not, and then once that is clear I report as fast as possible.

**Comment by am4n0w4r** [comment] 2016-02-01 11:56
I see. Ok, I'll then modify report sender to better match this issue.

**Comment by am4n0w4r** [comment] 2016-02-02 15:20
Please send reports using 0.1.33 when focus issues rise again.

**Comment by fyahfox** [comment] 2016-02-03 15:31
just had it again few minutes ago

**Comment by fyahfox** [comment] 2016-02-03 15:32
and again 10 seconds ago (reported as well again)

**Comment by am4n0w4r** [comment] 2016-02-04 10:52
Does this happen only on one device or multiple? The strange thing is that the camera reports that autofocus mode is set normally, no errors shown.

**Comment by fyahfox** [comment] 2016-02-04 13:03
Well, I only have one phone. But I know others had the focus issue as well...

**Comment by am4n0w4r** [comment] 2016-02-05 17:53
Please test in 0.1.34, changed focusing mode; Please report if not working;

**Comment by fyahfox** [comment] 2016-02-09 15:38
Another report sent 30 seconds ago

**Comment by am4n0w4r** [comment] 2016-02-25 17:04
Changed camera initialization mechanism in 0.1.39, this may help, as I'm not sure where is the problem, all reports say initialization is passing good and this is not reproducible on our side for a long time.

**Comment by fyahfox** [comment] 2016-02-26 10:40
0.1.39
Ok, it still happens (report send few seconds ago).
But I guess this is a problem with my phone if nobody else experiences this.

**Comment by kmiliak** [comment] 2016-04-18 13:32
Guys, could you close this task?
I guess it could not be reproduced by other testers.

**Closed** 2016-04-20 09:28 UTC
Labels: bug, mustfix
