### ISSUE TITLE
Deleting accounts is buggy

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#179] opened 2016-03-26 06:05 UTC
1.0.44

When I delete multiple accounts, it deletes the wrong accounts after the 1st deletion, not the one for which I clicked on the red cross.

**Comment by am4n0w4r** [comment] 2016-03-28 15:25
I can't reproduce this, all accounts are deleted exactly as clicked, could you please write the steps to reproduce this?

**Comment by fyahfox** [comment] 2016-04-04 10:47
I have 7 accounts in my wallet:
![photo_2016-04-04_12-45-28](https://cloud.githubusercontent.com/assets/6625264/14245668/243ade00-fa63-11e5-8365-52b9d28cbabe.jpg)

- click "Edit" in the account list
- delete "Multisig testing" -> works fine
- delete "Cosigner 1" -> ERROR: "Cosigner 2" gets deleted instead

**Comment by am4n0w4r** [comment] 2016-04-04 13:26
Ok, I see, thanks. Actually, Cosigner 2 is _shown_ as deleted but Cosigner 1 is deleted physically. I'll look into this issue.

**Comment by am4n0w4r** [comment] 2016-04-05 08:50
Fixed in 1.0.47;

**Closed** 2016-06-08 11:30 UTC
Labels: bug, mustfix, resolved
