### ISSUE TITLE
CREATE ACCOUNT page - Enter Private Key field issues

### ISSUE THREAD

**Issue by Xpedite** [NewEconomyMovement/NEMAndroidApp#23] opened 2015-10-08 05:37 UTC
When manually importing a private key in the create account page the field behaves erroneously. 
Numeric characters can't be entered and pressing backspace, copies existing values in stead of removing them. 
Copy/paste import is possible without issues. 

Device info:
Android version: 4.2.2

**Comment by fyahfox** [comment] 2015-10-08 09:00
I can enter 0-9 and a-f without problems. Backspace also works for me.

Also Android 4.2.2

**Comment by Xpedite** [comment] 2015-10-09 10:56
Verified issues on other device ( also Android 4.2.2) although behaviour is not exactly the same. But it's not working as expected. It may be related to auto correction so I will investigate that and report further.

**Comment by am4n0w4r** [comment] 2015-10-12 12:14
Confirmed on stock LG keyboard with word suggestion and auto correction on.

**Comment by lcharles123** [comment] 2015-10-21 23:48
I have same problem, on Android 4.4, Android Keyboard AOSP, it happens also when I try to add a new contact, I reported in #35

**Comment by am4n0w4r** [comment] 2015-12-09 17:27
Resolved in 0.1.24

**Comment by fyahfox** [comment] 2015-12-09 23:30
@Xpedite can you confirm?

**Comment by fyahfox** [comment] 2015-12-17 17:08
I guess not. If so, please comment/reopen. I cannot reproduce this issue.

**Closed by fyahfox** 2015-12-17 17:08 UTC

**Comment by MatCAlves** [comment] 2016-07-17 15:30
I am also with this issue here. When I try to type some characters that I believe are not acceptable like this interval of letters G - Z, nothing is really shown, but it is different when typing numbers or A - F letters. There are some kind of residual memory problem that makes some characters be typed more than once. Here is an example:

KB Key / Output:

[1] / 1
[a] / 1a
[2] / 1a2
[b] / 1a2b
[3] / 1a2b3
[g] /  
[i] /  

Final result:
![screenshot_2016-07-17-12-20-50](https://cloud.githubusercontent.com/assets/20224023/16901426/b4dfcd32-4c19-11e6-82f5-6aad19347e2e.png)

Device specifications:
Samsung Galaxy On7
Android 5.1.1
Kernel: 3.10.49
CPU: Qualcomm Snapdragon 400/410 1.2Ghs x4
NEM App version: 1.0.49.b3200

**Comment by am4n0w4r** [comment] 2016-07-20 09:39
@MatCAlves it seems like Samsung phones still just ignore instructions not to enable autocorrect.
Fixed in 1.0.51, please test when available;

**Comment by MatCAlves** [comment] 2016-07-20 14:40
Yes. It is a bug that really happens on Samsung stock keyboards. I disabled Predictive text option and tried to type the import key and it worked perfectly. 

![tmp_22269-screenshot_2016-07-20-11-30-03-650566321](https://cloud.githubusercontent.com/assets/20224023/16990500/8fbbbfb4-4e6e-11e6-86b7-ba4abeadffb4.png)

**Comment by MatCAlves** [comment] 2016-07-26 18:30
Confirmed. This issue was fixed on version 1.0.51.b3315 of the app.
