### ISSUE TITLE
Chat message gets displayed in the wrong chat!

### ISSUE THREAD

**Issue by Braintecho** [NewEconomyMovement/NEMAndroidApp#169] opened 2016-02-18 03:47 UTC
1. A message, I sent to Person A gets shown in dashboard as message for Person B, reproducable, atleast with the same msg.
&
2. It is in place for a tx of 10 XEM I received.

Happened when I just scrolled a bit up and down. Extremely weird..but see yourself. Eyecatching term "beluga supply".
HTC ONE X
Android 4.2.2
Version 0.1.36

![screenshot_2016-02-18-04-32-58](https://cloud.githubusercontent.com/assets/16880923/13133267/20c2f772-d5fa-11e5-9f59-c7036613ada5.png)
![screenshot_2016-02-18-04-33-11](https://cloud.githubusercontent.com/assets/16880923/13133272/26339824-d5fa-11e5-9e4c-56e4cb225391.png)
![screenshot_2016-02-18-04-33-39](https://cloud.githubusercontent.com/assets/16880923/13133275/2b7df6e4-d5fa-11e5-8a04-30dbb1492970.png)

**Comment by jabo38** [comment] 2016-02-18 07:13
can you write clear steps on how to reproduce this for the dev?

**Comment by Braintecho** [comment] 2016-02-18 07:37
A) It happened after I made acc cosig #1 a cosignatory of acc multisig #1 
B) You enter the account, everything is displayed normally, I scroll down to the bottom and back up. This leads to the msg of the wrong tx get shown in the wrong place.
 If I go back to accounts and back in its normal, but happens again if I repeat B...and so on

**Comment by fyahfox** [comment] 2016-02-19 22:08
i can't reproduce it by scrolling down and up again inside the dashboard of an account.
can you reproduce it for 0.1.38?

this is a pretty serious issue though, so we should find the cause.

**Comment by Braintecho** [comment] 2016-02-20 16:47
After a while I couldn´t reproduce it anymore even with 0.1.36. Im trying around with 0.1.38 but I couldn´t figure out exactly how this happened nor how to make it happen again.

**Comment by am4n0w4r** [comment] 2016-02-22 11:32
Requirements to reproduce:
Dashboard with more items than fits into window.
Top dashboard item should have no message.
Hidden bottom dashboard items should have messages.
1. Scroll dashboard down so second top item gets cut (means that first is hidden completely).
2. Scroll back to top - the first item should be without message.
Resolved in 0.1.39;

**Comment by fyahfox** [comment] 2016-02-23 10:18
Great! Can you confirm braintecho?

**Comment by Braintecho** [comment] 2016-05-12 20:16
NCVEVJSXVSEMH7KPKBBMP7EHL3RWG3EYNMPPINMI

**Comment by jabo38** [comment] 2016-05-23 15:41
bounty paid 
tx 91b4a371d6269bd24486258c524c9ae1252740e453e585ad9dabbfc6ab8ee3dc

**Closed** 2016-06-08 13:23 UTC
Labels: bug, mustfix, resolved
